config/routes.rb
Rails.application.routes.draw do
  root :to => 'schedules#index'
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  validate :check_dates_relation
  validates :whole_day, inclusion: [true, false]

  def check_dates_relation
    unless self.date_start.nil? || self.date_end.nil?  # 両方の日付が空白でない場合
      if self.date_start > self.date_end
        errors.add(:date_end, "は開始日以降にしてください")
      end
    end
  end

  def display_whole_day
    self.whole_day ? '○' : ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to schedules_path
    else
      flash.now[:alert] = "登録できませんでした"
      render "new"
    end
  end

  def show
    @schedule = Schedule.find(params[:id])
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(schedule_params)
      flash[:notice] = "スケジュールを更新しました"
      redirect_to schedules_path
    else
      flash.now[:alert] = "更新できませんでした"
      render "edit"
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to schedules_path
  end

  private

  def schedule_params
    params.require(:schedule).permit(:title, :date_start, :date_end, :whole_day, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails　スケジュール管理アプリ</h1>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <p>今日の日付：<%= Time.now.to_s(:date_jp) %></p>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>

<% if flash.now[:alert] %>
  <p class="alert"><%= flash.now[:alert] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :date_start, "開始日" %></th>
      <td><%= f.date_field :date_start %></td>
    </tr>

    <tr>
      <th><%= f.label :date_end, "終了日" %></th>
      <td><%= f.date_field :date_end %></td>
    </tr>

    <tr>
      <th><%= f.label :whole_day, "終日" %></th>
      <td><%= f.check_box :whole_day, {}, "true", "false" %></td>
    </tr>

    <tr>
      <th><%= f.label :memo, "メモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "編集完了"%></li>
      <li><%= link_to "一覧へ戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧（予定の数：<%= @schedules.count %>）</h2>
<p></p>

<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.date_start.to_s(:date_jp) %></td>
        <td><%= schedule.date_end.to_s(:date_jp) %></td>
        <td><%= schedule.display_whole_day %></td>
        <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
        <td><%= link_to "詳細", schedule_path(schedule) %></td>
        <td><%= link_to "編集", edit_schedule_path(schedule) %></td>
        <td><%= link_to "削除", schedule_path(schedule), method: :delete,
          data: {confirm: "本当に削除しますか？"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "新規登録", new_schedule_path %></p>

app/views/schedules/new.html.erb
<h2>スケジュール新規作成</h2>

<% if flash.now[:alert] %>
  <p class="alert"><%= flash.now[:alert] %></p>
<% end %>

<%= render "shared/error", obj: @schedule %>

<%= form_with model: @schedule do |f| %>
  <table>
    <tr>
      <th><%= f.label :title, "タイトル" %></th>
      <td><%= f.text_field :title %></td>
    </tr>

    <tr>
      <th><%= f.label :date_start, "開始日" %></th>
      <td><%= f.date_field :date_start %></td>
    </tr>

    <tr>
      <th><%= f.label :date_end, "終了日" %></th>
      <td><%= f.date_field :date_end %></td>
    </tr>

    <tr>
      <th><%= f.label :whole_day, "終日" %></th>
      <td><%= f.check_box :whole_day, {}, "true", "false" %></td>
    </tr>

    <tr>
      <th><%= f.label :memo, "メモ" %></th>
      <td><%= f.text_area :memo %></td>
    </tr>
  </table>

  <div>
    <ul>
      <li><%= f.submit "登録"%></li>
      <li><%= link_to "一覧へ戻る", schedules_path %></li>
    </ul>
  </div>
<% end %>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>

<table>
  <tr>
    <th><%= "タイトル" %></th>
    <td><%= @schedule.title %></td>
  </tr>

  <tr>
    <th><%= "開始日" %></th>
    <td><%= @schedule.date_start.to_s(:date_jp) %></td>
  </tr>

  <tr>
    <th><%= "終了日" %></th>
    <td><%= @schedule.date_end.to_s(:date_jp) %></td>
  </tr>

  <tr>
    <th><%= "終日" %></th>
    <td><%= @schedule.display_whole_day %></td>
  </tr>

  <tr>
    <th><%= "作成日時" %></th>
    <td><%= @schedule.created_at.to_s(:datetime_jp) %></td>
  </tr>

  <tr>
    <th><%= "更新日時" %></th>
    <td><%= @schedule.updated_at.to_s(:datetime_jp) %></td>
  </tr>

  <tr>
    <th><%= "メモ" %></th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>

<div>
  <ul>
    <li><%= link_to "一覧へ戻る", schedules_path %></li>
    <li><%= link_to "編集する", edit_schedule_path(@schedule) %></li>
    <li><%= link_to "削除する", schedule_path(@schedule), method: :delete,
      data: {confirm: "本当に削除しますか？"} %></li>
  </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>